### ISSUE TITLE
Incompatibility with Create Fabric

### ISSUE THREAD

**Issue by Tempest-5ky** [Bendimester23/better-fletching#1]
Game crashes on start when Create Fabric is launched alongside Better Archery.
Appears to be an incompatibility between Create's Porting-lib and Better Archery.

Error/crash: https://mclo.gs/dYn7hmL
Create Fabric: https://www.curseforge.com/minecraft/mc-mods/create-fabric

**Comment by Bendimester23** [comment]
Sorry for having to wait this long, I have just noticed this issue. I'll look into fixing it.

**Comment by Bendimester23** [comment]
Found and replaced the mixin which caused the issues.

**Comment by Bendimester23** [comment]
I uploaded a new version to Modrinth and Curseforge as well.

**Comment by Tempest-5ky** [comment]
Unfortunately, the new version seems to still break create AND break several other mods.
Crashlog: https://mclo.gs/swhWzcA

I know for sure that it's this mod causing the problem, as removing any other mentioned mods (ex. adorn) just makes different mods break in their place. 

From what I can see, it seems to be your RecipeManagerMixin causing the issue.

**Comment by Bendimester23** [comment]
https://github.com/Bendimester23/better-fletching/suites/8722282724/artifacts/394309934 this build should work.
